language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install libffi-dev
  - pip install discord.py[voice]
  - pip install youtube-dl
  - pip install dataset
  - pip install simpleeval
