language: python
python:
  - "3.5"
  # PyPy versions
  - "pypy"  # PyPy2 2.5.0
  - "pypy3" # Pypy3 2.4.0
  - "pypy-5.3.1"
# command to install dependencies
install:
  - pip install libffi-dev
  - pip install discord.py[voice]
  - pip install youtube-dl
  - pip install dataset
  - pip install simpleeval
